--------------------------------------------------------
--  DDL for Sequence EDU_MATRICULA_CURSOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CLARTECH"."EDU_MATRICULA_CURSOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
