--------------------------------------------------------
--  DDL for Table EDU_ALUMNOS
--------------------------------------------------------

  CREATE TABLE "CLARTECH"."EDU_ALUMNOS" 
   (	"ALU_ID" NUMBER(8,0), 
	"DNI" NUMBER(8,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(25 BYTE), 
	"EDAD" NUMBER(2,0), 
	"GENERO" VARCHAR2(10 BYTE), 
	"PAIS_ID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
GRANT SELECT, INSERT, UPDATE ON "CLARTECH"."EDU_ALUMNOS" TO "DEVASCH";
