--------------------------------------------------------
--  DDL for Table EDU_MATRICULAS
--------------------------------------------------------

  CREATE TABLE "CLARTECH"."EDU_MATRICULAS" 
   (	"MAT_ID" NUMBER(8,0), 
	"ALU_ID" NUMBER(8,0), 
	"FECHA" DATE, 
	"TOTAL" NUMBER(8,2), 
	"USUARIO" VARCHAR2(100 BYTE), 
	"OBSERVACIONES" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT, INSERT, UPDATE ON "CLARTECH"."EDU_MATRICULAS" TO "DEVASCH";
