--------------------------------------------------------
--  DDL for Table EDU_MATRICULA_CURSOS
--------------------------------------------------------

  CREATE TABLE "CLARTECH"."EDU_MATRICULA_CURSOS" 
   (	"MAT_CURSOS_ID" NUMBER(8,0), 
	"MAT_ID" NUMBER(8,0), 
	"CURSO_ID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
GRANT SELECT, INSERT, UPDATE ON "CLARTECH"."EDU_MATRICULA_CURSOS" TO "DEVASCH";