DROP SEQUENCE "ORDSDEMO"."DEVORA_LOGGER_SEQUENCE$";
DROP TABLE "ORDSDEMO"."DEPT" cascade constraints;
DROP TABLE "ORDSDEMO"."EMP" cascade constraints;
DROP TABLE "ORDSDEMO"."TestCollection1" cascade constraints;
DROP TABLE "ORDSDEMO"."TestCollection11" cascade constraints;
DROP TABLE "ORDSDEMO"."TestCollection111" cascade constraints;
DROP TABLE "ORDSDEMO"."TestCollection1111" cascade constraints;
DROP TABLE "ORDSDEMO"."TestCollection2" cascade constraints;
DROP TABLE "ORDSDEMO"."TestCollection3" cascade constraints;
DROP TABLE "ORDSDEMO"."TestCollection31" cascade constraints;
DROP TABLE "ORDSDEMO"."T1" cascade constraints;

DROP TABLE "ORDSDEMO"."DEVORA_LOGGER$" cascade constraints;
DROP TABLE "ORDSDEMO"."USER_VALIDATE" cascade constraints;

DROP TABLE "ORDSDEMO"."BRICKS" cascade constraints;
DROP TABLE "ORDSDEMO"."COLOURS" cascade constraints;
DROP TABLE "ORDSDEMO"."FIRMA" cascade constraints;


DROP PACKAGE "ORDSDEMO"."BLOG_ANGEL";
DROP PACKAGE "ORDSDEMO"."CALLER_CRUDWSDEPT";
DROP PACKAGE "ORDSDEMO"."MY_GLOBALS";
DROP PACKAGE "ORDSDEMO"."devora_logger_pack$";

DROP PACKAGE BODY "ORDSDEMO"."BLOG_ANGEL";
DROP PACKAGE BODY "ORDSDEMO"."CALLER_CRUDWSDEPT";
DROP PACKAGE BODY "ORDSDEMO"."MY_GLOBALS";
DROP PACKAGE BODY "ORDSDEMO"."devora_logger_pack$";


DROP SYNONYM "PUBLIC"."USER_ORDS_CLIENTS";
DROP SYNONYM "PUBLIC"."DBMS_OUTPUT";
DROP SYNONYM "PUBLIC"."APEX_APPLICATION";
DROP SYNONYM "PUBLIC"."APEX_APPLICATION_GLOBAL";
DROP SYNONYM "PUBLIC"."APEX_COLLECTION";
DROP SYNONYM "PUBLIC"."APEX_DEBUG";
DROP SYNONYM "PUBLIC"."APEX_JSON";
DROP SYNONYM "PUBLIC"."APEX_UTIL";
DROP SYNONYM "PUBLIC"."APEX_WEB_SERVICE";
DROP SYNONYM "PUBLIC"."DUAL";
DROP SYNONYM "PUBLIC"."NV";
DROP SYNONYM "PUBLIC"."PLITBLM";
DROP SYNONYM "PUBLIC"."V";
DROP SYNONYM "PUBLIC"."DBMS_SCHEDULER";
