--------------------------------------------------------
-- Archivo creado  - miércoles-febrero-24-2021   
--------------------------------------------------------
@DROPS\DROP.sql
@SEQUENCES\EDU_ALUMNOS_SEQ.sql
@SEQUENCES\EDU_CURSOS_SEQ.sql
@SEQUENCES\EDU_DEPARTAMENTOS_SEQ.sql
@SEQUENCES\EDU_MATRICULA_CURSOS_SEQ.sql
@SEQUENCES\EDU_MATRICULAS_SEQ.sql
@SEQUENCES\EDU_PAISES_SEQ.sql
@SEQUENCES\EDU_PROFESORES_SEQ.sql
@TABLES\EDU_ALUMNOS.sql
@TABLES\EDU_CURSOS.sql
@TABLES\EDU_DEPARTAMENTOS.sql
@TABLES\EDU_MATRICULA_CURSOS.sql
@TABLES\EDU_MATRICULAS.sql
@TABLES\EDU_PAISES.sql
@TABLES\EDU_PROFESORES.sql

@DATA_TABLE\EDU_ALUMNOS.sql
@DATA_TABLE\EDU_CURSOS.sql
@DATA_TABLE\EDU_DEPARTAMENTOS.sql
@DATA_TABLE\EDU_MATRICULA_CURSOS.sql
@DATA_TABLE\EDU_MATRICULAS.sql
@DATA_TABLE\EDU_PAISES.sql
@DATA_TABLE\EDU_PROFESORES.sql

@TRIGGERS\BI_EDU_ALUMNOS.sql
@TRIGGERS\BI_EDU_CURSOS.sql
@TRIGGERS\BI_EDU_DEPARTAMENTOS.sql
@TRIGGERS\BI_EDU_MATRICULAS.sql
@TRIGGERS\BI_EDU_PAISES.sql
@TRIGGERS\BI_EDU_PROFESORES.sql
@TRIGGERS\BI_MATRICULA_CURSOS.sql
