-- Create new user and data CLARTECH
-- ejecutar con sys as sysdba.  Hacerlo con sqlplus con sys as sysdba. 
CREATE USER CLARTECH IDENTIFIED BY CLARTECH DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER USER CLARTECH  ACCOUNT UNLOCK identified by oracle1;
GRANT CREATE SESSION TO CLARTECH;
GRANT CREATE VIEW, CREATE TABLE, CREATE PROCEDURE, CREATE SEQUENCE , CREATE TRIGGER TO CLARTECH;

