--------------------------------------------------------
--  DDL for Table DEVORA_LOGGER$
--------------------------------------------------------

  CREATE TABLE "ORDSDEMO"."DEVORA_LOGGER$" 
   (	"ID" NUMBER, 
	"CURR_TIMESTAMP" TIMESTAMP (6), 
	"APP_TITLE" VARCHAR2(100 BYTE), 
	"APP_USER" VARCHAR2(100 BYTE), 
	"APP_SESSION" VARCHAR2(100 BYTE), 
	"BACK_TRACE" VARCHAR2(4000 BYTE), 
	"DBG_MSG" VARCHAR2(4000 BYTE), 
	"ERROR_STACK" VARCHAR2(4000 BYTE), 
	"CALL_STACK" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "ORDSDEMO"."DEVORA_LOGGER$" TO "DEVASCH";
