--------------------------------------------------------
--  DDL for Table TestCollection1111
--------------------------------------------------------

  CREATE TABLE "ORDSDEMO"."TestCollection1111" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATED_ON" TIMESTAMP (6) DEFAULT sys_extract_utc(SYSTIMESTAMP), 
	"LAST_MODIFIED" TIMESTAMP (6) DEFAULT sys_extract_utc(SYSTIMESTAMP), 
	"VERSION" VARCHAR2(255 BYTE), 
	"JSON_DOCUMENT" BLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("JSON_DOCUMENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ;
