REM INSERTING into CLARTECH.EDU_PAISES
SET DEFINE OFF;
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (1,'Antigua y Barbuda');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (2,'Argentina');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (3,'Bahamas');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (4,'Barbados');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (5,'Belice');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (6,'Bolivia');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (7,'Brasil');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (8,'Canadá');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (9,'Chile');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (10,'Colombia');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (11,'Costa Rica');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (12,'Cuba');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (13,'Dominica');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (14,'Ecuador');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (15,'El Salvador');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (16,'Estados Unidos');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (17,'Granada');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (18,'Guatemala');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (19,'Guyana');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (20,'Haití');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (21,'Honduras');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (22,'Jamaica');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (23,'Mexico');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (24,'Nicaragua');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (25,'Panamá');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (26,'Paraguay');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (27,'Perú');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (28,'República Dominicana');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (29,'San Cristobal y Nieves');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (30,'San Vicente y las Granadinas');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (31,'Santa Lucía');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (32,'Surinam');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (33,'Trinidad y Tobago');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (34,'Uruguay');
Insert into CLARTECH.EDU_PAISES (PAIS_ID,NOMBRE_PAIS) values (35,'Venezuela');
