REM INSERTING into CLARTECH.EDU_MATRICULA_CURSOS
SET DEFINE OFF;
Insert into CLARTECH.EDU_MATRICULA_CURSOS (MAT_CURSOS_ID,MAT_ID,CURSO_ID) values (104,122,2);
Insert into CLARTECH.EDU_MATRICULA_CURSOS (MAT_CURSOS_ID,MAT_ID,CURSO_ID) values (105,122,4);
Insert into CLARTECH.EDU_MATRICULA_CURSOS (MAT_CURSOS_ID,MAT_ID,CURSO_ID) values (101,121,4);
Insert into CLARTECH.EDU_MATRICULA_CURSOS (MAT_CURSOS_ID,MAT_ID,CURSO_ID) values (102,121,3);
Insert into CLARTECH.EDU_MATRICULA_CURSOS (MAT_CURSOS_ID,MAT_ID,CURSO_ID) values (103,122,41);
Insert into CLARTECH.EDU_MATRICULA_CURSOS (MAT_CURSOS_ID,MAT_ID,CURSO_ID) values (121,141,81);
Insert into CLARTECH.EDU_MATRICULA_CURSOS (MAT_CURSOS_ID,MAT_ID,CURSO_ID) values (122,141,2);
Insert into CLARTECH.EDU_MATRICULA_CURSOS (MAT_CURSOS_ID,MAT_ID,CURSO_ID) values (123,142,81);
Insert into CLARTECH.EDU_MATRICULA_CURSOS (MAT_CURSOS_ID,MAT_ID,CURSO_ID) values (124,142,2);
