DROP SEQUENCE "CLARTECH"."EDU_ALUMNOS_SEQ";
DROP SEQUENCE "CLARTECH"."EDU_CURSOS_SEQ";
DROP SEQUENCE "CLARTECH"."EDU_DEPARTAMENTOS_SEQ";
DROP SEQUENCE "CLARTECH"."EDU_MATRICULA_CURSOS_SEQ";
DROP SEQUENCE "CLARTECH"."EDU_MATRICULAS_SEQ";
DROP SEQUENCE "CLARTECH"."EDU_PAISES_SEQ";
DROP SEQUENCE "CLARTECH"."EDU_PROFESORES_SEQ";

DROP TABLE "CLARTECH"."EDU_ALUMNOS" cascade constraints;
DROP TABLE "CLARTECH"."EDU_CURSOS" cascade constraints;
DROP TABLE "CLARTECH"."EDU_DEPARTAMENTOS" cascade constraints;
DROP TABLE "CLARTECH"."EDU_MATRICULA_CURSOS" cascade constraints;
DROP TABLE "CLARTECH"."EDU_MATRICULAS" cascade constraints;
DROP TABLE "CLARTECH"."EDU_PAISES" cascade constraints;
DROP TABLE "CLARTECH"."EDU_PROFESORES" cascade constraints;
