--------------------------------------------------------
-- Archivo creado  - sábado-febrero-27-2021   a las 1:11 pm. 1:20pm
--------------------------------------------------------

@DROPS\DROP.sql

@SEQUENCES\DEVORA_LOGGER_SEQUENCE.sql

@TABLES\DEPT.sql
@TABLES\DEVORA_LOGGER.sql
@TABLES\EMP.sql
@TABLES\TestCollection1.sql
@TABLES\TestCollection11.sql
@TABLES\TestCollection111.sql
@TABLES\TestCollection1111.sql
@TABLES\TestCollection2.sql
@TABLES\TestCollection3.sql
@TABLES\TestCollection31.sql
@TABLES\T1.sql
@TABLES\USER_VALIDATE.sql
@TABLES\BRICKS.sql
@TABLES\COLOURS.sql
@TABLES\FIRMA.sql

@VIEWS\APEX_APPLICATION_PAGES.sql
@DATA_TABLE\DEPT.sql
@DATA_TABLE\DEVORA_LOGGER.sql
@DATA_TABLE\EMP.sql
@DATA_TABLE\TestCollection1.sql
@DATA_TABLE\TestCollection11.sql
@DATA_TABLE\TestCollection111.sql
@DATA_TABLE\TestCollection1111.sql
@DATA_TABLE\TestCollection2.sql
@DATA_TABLE\TestCollection3.sql
@DATA_TABLE\TestCollection31.sql
@DATA_TABLE\T1.sql
@DATA_TABLE\USER_VALIDATE.sql
@DATA_TABLE\BRICKS.sql
@DATA_TABLE\COLOURS.sql
@DATA_TABLE\FIRMA.sql

@INDEXES\SYS_C0012483.sql
@INDEXES\SYS_C0012638.sql
@INDEXES\SYS_C0012652.sql
@INDEXES\SYS_C0012747.sql
@INDEXES\SYS_C0012753.sql
@INDEXES\SYS_C0013080.sql
@INDEXES\SYS_C0013083.sql

@PACKAGES\MY_GLOBALS.sql
@PACKAGES\BLOG_ANGEL.sql
@PACKAGES\MYDEVORA_LOGGER_PACK.sql
@PACKAGES\CALLER_CRUDWSDEPT.sql

@PACKAGE_BODIES\MY_GLOBALS.sql
@PACKAGE_BODIES\BLOG_ANGEL.sql
@PACKAGE_BODIES\MYDEVORA_LOGGER_PACK.sql
@PACKAGE_BODIES\CALLER_CRUDWSDEPT.sql

@CONSTRAINTS\TestCollection1.sql
@CONSTRAINTS\TestCollection11.sql
@CONSTRAINTS\TestCollection111.sql
@CONSTRAINTS\TestCollection1111.sql
@CONSTRAINTS\TestCollection2.sql
@CONSTRAINTS\TestCollection3.sql
@CONSTRAINTS\TestCollection31.sql
