--------------------------------------------------------
-- Archivo creado  - sábado-febrero-27-2021   a las 1:11 pm. 1:20pm
--------------------------------------------------------
ALTER SESSION SET CONTAINER=xepdb1;

ALTER SESSION SET CURRENT_SCHEMA = ORDSDEMO;

@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DROPS\DROP.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\SEQUENCES\DEVORA_LOGGER_SEQUENCE.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\TABLES\DEPT.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\TABLES\DEVORA_LOGGER.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\TABLES\EMP.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\TABLES\TestCollection1.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\TABLES\TestCollection11.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\TABLES\TestCollection111.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\TABLES\TestCollection1111.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\TABLES\TestCollection2.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\TABLES\TestCollection3.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\TABLES\TestCollection31.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\TABLES\T1.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\VIEWS\APEX_APPLICATION_PAGES.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DATA_TABLE\DEPT.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DATA_TABLE\DEVORA_LOGGER.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DATA_TABLE\EMP.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DATA_TABLE\TestCollection1.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DATA_TABLE\TestCollection11.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DATA_TABLE\TestCollection111.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DATA_TABLE\TestCollection1111.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DATA_TABLE\TestCollection2.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DATA_TABLE\TestCollection3.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DATA_TABLE\TestCollection31.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\DATA_TABLE\T1.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\INDEXES\SYS_C0012483.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\INDEXES\SYS_C0012638.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\INDEXES\SYS_C0012652.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\INDEXES\SYS_C0012747.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\INDEXES\SYS_C0012753.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\INDEXES\SYS_C0013080.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\INDEXES\SYS_C0013083.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\PROCEDURES\GET_CLIENT_CREDENTIALS.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\PACKAGES\BLOG_ANGEL.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\PACKAGES\CALLER_CRUDWSDEPT.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\PACKAGES\DEVORA_LOGGER_PACK.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\PACKAGES\MY_GLOBALS.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\PACKAGE_BODIES\BLOG_ANGEL.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\PACKAGE_BODIES\CALLER_CRUDWSDEPT.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\PACKAGE_BODIES\DEVORA_LOGGER_PACK.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\PACKAGE_BODIES\MY_GLOBALS.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\SYNONYMS\USER_ORDS_CLIENTS.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\SYNONYMS\APEX_APPLICATION.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\SYNONYMS\APEX_APPLICATION_GLOBAL.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\SYNONYMS\APEX_COLLECTION.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\SYNONYMS\APEX_DEBUG.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\SYNONYMS\APEX_JSON.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\SYNONYMS\APEX_UTIL.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\SYNONYMS\APEX_WEB_SERVICE.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\SYNONYMS\NV.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\SYNONYMS\V.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\CONSTRAINTS\TestCollection1.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\CONSTRAINTS\TestCollection11.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\CONSTRAINTS\TestCollection111.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\CONSTRAINTS\TestCollection1111.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\CONSTRAINTS\TestCollection2.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\CONSTRAINTS\TestCollection3.sql
@C:\working21\OraAPEX\backup-apps\Restore3webapps-apex-1\oraschemas\ordsdemo1\CONSTRAINTS\TestCollection31.sql
