REM INSERTING into ORDSDEMO.COLOURS
SET DEFINE OFF;
Insert into ORDSDEMO.COLOURS (COLOUR_NAME,MINIMUM_BRICKS_NEEDED) values ('blue',2);
Insert into ORDSDEMO.COLOURS (COLOUR_NAME,MINIMUM_BRICKS_NEEDED) values ('green',3);
Insert into ORDSDEMO.COLOURS (COLOUR_NAME,MINIMUM_BRICKS_NEEDED) values ('red',2);
Insert into ORDSDEMO.COLOURS (COLOUR_NAME,MINIMUM_BRICKS_NEEDED) values ('orange',1);
Insert into ORDSDEMO.COLOURS (COLOUR_NAME,MINIMUM_BRICKS_NEEDED) values ('yellow',1);
Insert into ORDSDEMO.COLOURS (COLOUR_NAME,MINIMUM_BRICKS_NEEDED) values ('purple',1);
