REM INSERTING into ORDSDEMO.DEPT
SET DEFINE OFF;
Insert into ORDSDEMO.DEPT (DEPTNO,DNAME,LOC) values (10,'ACCOUNTING','NEW YORK');
Insert into ORDSDEMO.DEPT (DEPTNO,DNAME,LOC) values (20,'RESEARCH','DALLAS');
Insert into ORDSDEMO.DEPT (DEPTNO,DNAME,LOC) values (30,'SALESs','CHICAGO');
Insert into ORDSDEMO.DEPT (DEPTNO,DNAME,LOC) values (40,'OPERATIONS','BOSTON');
