-- Generated by SQLcl REST Data Services 20.4.2.0
-- Exported REST Definitions from ORDS Schema Version 20.3.0.r3011819
-- Schema: ORDSDEMO   Date: Tue Mar 09 15:17:46 CST 2021
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ORDSDEMO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'api2',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'empdep.v2',
      p_base_path      => '/empdep/v2/',
      p_items_per_page =>  10,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'empdep.v2',
      p_pattern        => 'departments',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'empdep.v2',
      p_pattern        => 'departments',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  5,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT deptno, dname, loc FROM dept ORDER BY deptno'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'empdep.v2',
      p_pattern        => 'departments',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'BEGIN
    DELETE FROM dept
    WHERE deptno = :pn_dept_no;
    commit;
    END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'DELETE',
      p_name               => 'department_number',
      p_bind_variable_name => 'pn_dept_no',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'DELETE',
      p_name               => 'result_message',
      p_bind_variable_name => 'pv_result',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'DELETE',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'pn_status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'empdep.v2',
      p_pattern        => 'departments',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'BEGIN
  INSERT INTO dept (deptno, dname, loc) VALUES (:pn_dept_no, :pv_dept_name, :pv_location);
  commit;
 END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'POST',
      p_name               => 'department_name',
      p_bind_variable_name => 'pv_dept_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'POST',
      p_name               => 'department_number',
      p_bind_variable_name => 'pn_dept_no',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'POST',
      p_name               => 'location_name',
      p_bind_variable_name => 'pv_location',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'POST',
      p_name               => 'result_message',
      p_bind_variable_name => 'pv_result',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'POST',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'pn_status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'empdep.v2',
      p_pattern        => 'departments',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'BEGIN
        UPDATE dept
        SET dname = :pv_dept_name, loc = :pv_location
        WHERE deptno = :pn_dept_no;
        commit;
        END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'PUT',
      p_name               => 'department_name',
      p_bind_variable_name => 'pv_dept_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'PUT',
      p_name               => 'department_number',
      p_bind_variable_name => 'pn_dept_no',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'PUT',
      p_name               => 'location_name',
      p_bind_variable_name => 'pv_location',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'PUT',
      p_name               => 'result_message',
      p_bind_variable_name => 'pv_result',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'departments',
      p_method             => 'PUT',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'pn_status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'empdep.v2',
      p_pattern        => 'employees',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'empdep.v2',
      p_pattern        => 'employees',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT d.dname, e.ename, e.job, e.empno, e.hiredate, d.loc FROM emp e, dept d  WHERE e.deptno = d.deptno AND (:pn_deptno IS NULL OR d.deptno = :pn_deptno) ORDER BY d.dname, e.ename'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'empdep.v2',
      p_pattern            => 'employees',
      p_method             => 'GET',
      p_name               => 'department_number',
      p_bind_variable_name => 'pn_deptno',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v1',
      p_base_path      => '/rest/v1/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v1',
      p_pattern        => 'employees/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v1',
      p_pattern        => 'employees/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT * FROM emp'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v2',
      p_base_path      => '/rest/v2/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v2',
      p_pattern        => 'employees/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v2',
      p_pattern        => 'employees/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT * FROM emp'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v3',
      p_base_path      => '/rest/v3/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v3',
      p_pattern        => 'employees/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v3',
      p_pattern        => 'employees/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT * FROM emp'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v3',
      p_pattern        => 'employees/:empno',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v3',
      p_pattern        => 'employees/:empno',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT * FROM emp WHERE empno = :empno'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v3b',
      p_base_path      => '/rest/v3b/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v3b',
      p_pattern        => 'employees/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v3b',
      p_pattern        => 'employees/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT * FROM emp WHERE empno BETWEEN :empno_start AND :empno_end'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v3bb',
      p_base_path      => '/rest/v3bb/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v3bb',
      p_pattern        => 'employees/:empno_start/:empno_end',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v3bb',
      p_pattern        => 'employees/:empno_start/:empno_end',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT * FROM emp WHERE empno BETWEEN :empno_start AND :empno_end'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v3c',
      p_base_path      => '/rest/v3c/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v3c',
      p_pattern        => 'employees/:empno',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v3c',
      p_pattern        => 'employees/:empno',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT *
                         FROM   emp
                         WHERE  empno IN (SELECT * FROM TABLE(MY_GLOBALS.in_list(:empno)))
                         ORDER BY ename'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v4',
      p_base_path      => '/rest/v4/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v4',
      p_pattern        => 'employees/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v4',
      p_pattern        => 'employees/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'BEGIN 
MY_GLOBALS.get_emp_json;
        :status := 200;
      EXCEPTION
        WHEN OTHERS THEN
        :status := 400;
        :result_message  := ''en ords handler:  '' || SQLCODE  || ''--'' || SQLERRM ;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'rest-v4',
      p_pattern            => 'employees/',
      p_method             => 'GET',
      p_name               => 'pv_result',
      p_bind_variable_name => 'result_message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'rest-v4',
      p_pattern            => 'employees/',
      p_method             => 'GET',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v4',
      p_pattern        => 'employees/:empno',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v4',
      p_pattern        => 'employees/:empno',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'BEGIN MY_GLOBALS.get_emp_json(:empno); END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v5',
      p_base_path      => '/rest/v5/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v5',
      p_pattern        => 'employees/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v5',
      p_pattern        => 'employees/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'BEGIN MY_GLOBALS.get_emp_xml; END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v5',
      p_pattern        => 'employees/:empno',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v5',
      p_pattern        => 'employees/:empno',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'BEGIN MY_GLOBALS.get_emp_xml(:empno); END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v6',
      p_base_path      => '/rest/v6/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v6',
      p_pattern        => 'employees/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v6',
      p_pattern        => 'employees/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT * FROM emp'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v6',
      p_pattern        => 'employees/',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
                           my_globals.remove_employee(p_empno => :empno);
                         END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v6',
      p_pattern        => 'employees/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'BEGIN
                           my_globals.create_employee (p_empno    => :empno,
                                            p_ename    => :ename,
                                            p_job      => :job,
                                            p_mgr      => :mgr,
                                            p_hiredate => :hiredate,
                                            p_sal      => :sal,
                                            p_comm     => :comm,
                                            p_deptno   => :deptno);
                         END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v6',
      p_pattern        => 'employees/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
                           my_globals.amend_employee(p_empno    => :empno,
                                          p_ename    => :ename,
                                          p_job      => :job,
                                          p_mgr      => :mgr,
                                          p_hiredate => :hiredate,
                                          p_sal      => :sal,
                                          p_comm     => :comm,
                                          p_deptno   => :deptno);
                         END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v6',
      p_pattern        => 'employees/:empno',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v6',
      p_pattern        => 'employees/:empno',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT * FROM emp WHERE empno = :empno'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v7',
      p_base_path      => '/rest/v7/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v7',
      p_pattern        => 'departmentsjsonobject/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v7',
      p_pattern        => 'departmentsjsonobject/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'BEGIN
                           my_globals.CREATE_DEPARTMENTS_JSONOBJECT(p_data => :body);
                         END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v7',
      p_pattern        => 'departmentsjsontable/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v7',
      p_pattern        => 'departmentsjsontable/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
       my_globals.CREATE_DEPARTMENTS_JSONTABLE(p_data => :body);
        :status := 201;
        :result_message  := ''insersion ok !'' ;
        :forward_location := ''http://localhost:8080/ords/api2/rest/v8/departments/'';

      EXCEPTION
        WHEN OTHERS THEN
        :status := 400;
        :result_message  := ''en ords handler:  '' || SQLCODE  || ''--'' || SQLERRM ;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'rest-v7',
      p_pattern            => 'departmentsjsontable/',
      p_method             => 'POST',
      p_name               => 'pv_result',
      p_bind_variable_name => 'result_message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'rest-v7',
      p_pattern            => 'departmentsjsontable/',
      p_method             => 'POST',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v8',
      p_base_path      => '/rest/v8/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v8',
      p_pattern        => 'departments/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v8',
      p_pattern        => 'departments/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         =>
'SELECT d.dname AS "department_name",
                                d.deptno AS "department_number",
                                d.deptno AS "$self",
                                CURSOR(SELECT e.empno AS "employee_number",
                                              e.ename AS "employee_name",
                                              e.empno AS "$self"
                                       FROM   emp e
                                       WHERE  e.deptno = d.deptno
                                       ORDER BY e.empno) AS "employees"
                         FROM   dept d
                         ORDER BY d.dname'
      );


  COMMIT;
END;
